### ISSUE TITLE
No modules: E.g. 'requests' etc.; Request for more elaborate example tutorial

### ISSUE THREAD

**Issue by gtu78aed87t** [prenagha/patreon-mp3#1]
_Ima dumbass. I don't think I understand how to use the program really.._

**Log of what I did:**
- -Having the latest ‘brew’-version installed*
- ran ‘brew install python3’ in terminal
- ran ‘brew install pip3’ in terminal
- ran ‘pip3 install feedparser’ in terminal
- In ‘finder’: copied ‘config-sample.ini’ and renamed it ‘config.ini’
- copied my 'private RRS link'
- opened ‘config.ini’ with textEdit.app, edited and saved (see copy of its content farther below)
- In ‘finder’: right clicked, ran, permitted and launched ‘patreon-mp3.py’ in terminal

I received following error whitin the string of text in terminal:

Terminal:
```
import requests
ModuleNotFoundError: No module named 'requests'
```

config.ini:
```
RSSURL = https://www.patreon.com/rss/Pr*************en?auth=Ps**************************************2K_
Genre = Ma*****************ws
Album = Pa*******************en
DownloadPrefix = downloads/
```

**Update 1:** 
Ok I made some progress; i didn't get all three FeedParser, Requests and Eye3D had to be installed: 
- I ran 'pip3 install requests' and 'pip3 install eye3d'  in terminal, but had an error with the eye3d-installation.
- Then ran patreon-mp3-py over again and received missing 'magic' module this time:
`    import magic
ModuleNotFoundError: No module named 'magic'`
I assume the change from 'requests' to 'magic' was changed by the first one being solved

_Assumed suspect cause and solution for now:
Figure out why and how to install 'eye3d' properly -> Run 'patreon-mp3.py' over again._

**Update 2:**
- Read the error and copy-pasted following string in terminal:
/usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip
- ran ‘patreon-mp3.py’, but received the ‘magic’ error again
- Tried ‘pip3 install magic’. It didn’t work, but I received:
```
==> Searching for similarly named formulae...
These similarly named formulae were found:
graphicsmagick      imagemagick@6       magic-wormhole      somagic
imagemagick         libmagic            magic_enum          somagic-tools
```

_Well.. I have a new lead thread I suppose; figure out which one if any that resemble the 'magic'-module. Does any of these is installs require a system reboot maybe?_
 
**update 3:**
- Figured ‘libmagic’ might have something to do with python3
- Ran ‘brew install libmagic’
- Ran ‘patreon-mp3.py’ once over but to no avail: “No module named 'magic’”

_Can't reboot. I have some unfinished business I can't save or quit yet._

**update 4:**
- Ran the die with ‘pip install python-magic’ and ran over again and received ‘eye3d’-error
- Came to remember the initial obstacle not managing to install 'eye3d'
ran ’pip3 install eye3d’ and got:
```
ERROR: Could not find a version that satisfies the requirement eye3D (from versions: none)
ERROR: No matching distribution found for eye3D 
```
_Hm.. Re-evaluating an easier alternative to solution: **a)** download 153 mp3's manually **b)** give up, or **c)** shoot myself._ 

**Update 5:**
Pew.. That was close: I did a last web search and tried following:
- ‘brew install eye-d3’ - it installed. It provides a command-line tool (eyeD3) and a Python library (import eyed3) supposedly whatever that means. 
- Went mental and ran ‘sudo pip install eyeD3’ and got some yellow root warnings. Sheesh.. But something happened.
- Ran ‘patreon-mp3.py’ and got some jazz about ‘feed’ missing and more
- Reinstated [feed] at the start of the ‘config.ini’ again. Saved and ran. Received error:

Terminal:
```
File "/Users/***********workstation/Downloads/patreon-mp3-master/patreon-mp3.py", line 26, in <module>
    cfg = parser['feed']
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'feed'
```
_I see a link in the end of the tunnel below; Prenagha, thank you I'll try a little more._

**Update 6:**
Look mr. fancy-"-m pip"-guy: I’m on MacOS Mojave: 
- I ran 'easy_install --version, which responded ’setuptools 18.5’ and ‘Python 2.7’ etc.
- then ran ‘sudo easy_install pip’. And received:
```
Searching for pip
Reading https://pypi.python.org/simple/pip/
Couldn't find index page for 'pip' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for pip
error: Could not find suitable distribution for Requirement.parse('pip')
```
- Read a bit more and ran ‘curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py’
- Then ran ‘python get-pip.py’. Received:
```
ERROR: This script does not work on Python 2.7 The minimum supported Python version is 3.6. Please use https://bootstrap.pypa.io/pip/2.7/get-pip.py instead.
iMac:~ **********workstation$ 
```
- Read it and ran ‘curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py’
- Ran ‘python get-pip.py’. “Successfully installed pip-20.3.4 wheel-0.36.2”.
- Ran ‘pip --version’ to confirm. Got ‘pip 21.1.2 ’ and ‘python 3.9’
- Tried ‘patreon-mp3.py’ again. Received:
```
line 26, in <module>
    cfg = parser['feed']
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'feed'
```

_Now I suspect it is something with [feed] I don’t get. 
I tried both with and without again._

config.ini:
```
[feed]
RSSURL = https://www.patreon.com/rss/Pr*************en?auth=Ps**************************************2K_
Genre = Ma*****************ws
Album = Pa*******************en
DownloadPrefix = downloads/
```

_I don't get it. Not sure if the script is ment be with/or without "[feed]"? Neither what line 960 "getitem"-something is supposed to represent._ 

**Update 7:**
_If you don't hear from me again it's not because I'd fixed it to put it like that.._

**Comment by prenagha** [comment]
https://docs.python-requests.org/en/master/user/install/#install
